# Generated by Django 4.2 on 2025-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_useranswer_question_useranswer_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
