# Generated by Django 4.2 on 2025-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_useranswer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer4',
            new_name='option4',
        ),
    ]
